# debug, test, release
RunMode = "debug"
Swagger = true
PrintConfig = false

[Global]
AppName = "Govern"
AppIcon = "favicon.ico"
DateFormat = "2006-01-02"
DatetimeFormat = "2006-01-02 15:04:05"
TimeZone = "Asia/Shanghai"
OriginDomainFile = "config/domain.yaml"
OriginMenuFile = "config/menu.yaml"

[ServiceLog]
# If true, the use the custom logger.
Enable = false
# If true, then skip lo logger to os.Stdout.
SkipStdout = false
# If true, then logger to mongo database.
Log2Mongo = false
# Max value of the number of workers in the task queue.
MaxWorkers = 50
# Max value of the number of buffers in the task queue.
MaxBuffers = 10000

[CORS]
Enable = true
AllowOrigins = ["www.sfshf.com"]
AllowMethods = ["OPTIONS", "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
AllowHeaders = ["Origin", "Content-Length", "Content-Type", "Authorization"]
AllowCredentials = false
MaxAge = 43200

[GZIP]
Enable = false

[Root]
Account = "root"
Password = "12341234"

[MongoDB]
# Uri to the mongo database.
ServerUri = "mongodb://127.0.0.1:27017/govern?directConnection=true"
# The name of a database.
Database = "govern"

# 'redis://<user>:<password>@<host>:<port>/<db_number>'
# Or:
# 'unix://<user>:<password>@</path/to/redis.sock>?db=<db_number>'
[Redis]
Enable = false
Network = "tcp"
Addr = "127.0.0.1:6379"
Username = ""
Password = ""
DB = 0

[Cache]
Enable = true
IsLRU = true
MaxKeys = 10000
TTL = 15

[JWTAuth]
Enable = true
SigningKey = ""
Expired = 2592000 # 86400
Stored = false

[Casbin]
Enable = true
Debug = false
Model = "config/casbin_rbac.model"
AutoSave = true
AutoLoad = false
AutoLoadInternal = 60

[PicCaptcha]
Enable = false
Length = 4
Width = 680
Height = 450
MaxSkew = 1.0
DotCount = 10
Threshold = 100
Expiration = 60
RedisStore = false
RedisDB = 0
RedisPrefix = "PicCaptcha:"

[HTTP]
Host = "0.0.0.0"
Port = 8000
CertFile = ""
CertKeyFile = ""
ShutdownTimeout = 10
MaxContentLength = 8192
MaxLoggerLength = 8192






